[workspace]
resolver = "2"
members = [
    #
    "block-manager",
    "database",
    "gossip",
    "gql-server",
    "http-server",
    "message-router",
    "migration-tool",
    "network",
    "node",
    "node-helper",
    "proxy",
    "transport-layer",
]

package.version = "0.3.8"
package.edition = "2021"
package.rust-version = "1.83.0"
package.license = "Acki Nacki Node License"
package.license-file = "LICENSE.md"

[workspace.dependencies]
actix-web = { version = "4.8.0" }
anyhow = "1.0.80"
async-trait = { version = "0.1.85" }
bincode = "1.3.3"
clap = { version = "4.5.2", features = ["derive", "env"] }
futures = "0.3"
hex = "0.4.3"
lazy_static = "1.4.0"
num-bigint = { version = "0.4.6", features = ["serde"] }
num-traits = "0.2.19"
opentelemetry = "0.27"
opentelemetry-otlp = { version = "0.27", features = ["metrics"] }
opentelemetry_sdk = { version = "0.27", features = ["rt-tokio"] }
parking_lot = '0.12'
rcgen = "0.13"
rusqlite = { version = "0", features = ["bundled"] }
salvo = { version = "0.75", features = ["affix-state", "anyhow", "catch-panic", "logging", "quinn", "rustls", "serve-static", "test"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_with = "3.8.1"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.28"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = { version = "2.5.0", features = ["serde"] }
wtransport = { version = "0.5.0", features = ["dangerous-configuration"] }

chitchat = { git = "https://github.com/gosh-sh/chitchat.git", rev = "c3ac1874aac9479f1602c2a5a652873b4e4310c1" }
gosh_bls_lib = { git = "https://github.com/gosh-sh/gosh-bls-lib.git", tag = "0.4.0" }
lockfree = { git = 'https://github.com/tvmlabs/lockfree.git', package = 'lockfree' }
tvm_abi = { git = 'https://github.com/tvmlabs/tvm-sdk.git', tag = "v2.3.3.an" }
tvm_block = { git = 'https://github.com/tvmlabs/tvm-sdk.git', tag = "v2.3.3.an" }
tvm_block_json = { git = 'https://github.com/tvmlabs/tvm-sdk.git', tag = "v2.3.3.an" }
tvm_client = { git = 'https://github.com/tvmlabs/tvm-sdk.git', tag = "v2.3.3.an", default-features = false, features = ["std", 'rustls-tls-webpki-roots'] }
tvm_executor = { git = 'https://github.com/tvmlabs/tvm-sdk.git', tag = "v2.3.3.an", features = ['signature_with_id'] }
tvm_tl_codegen = { git = 'https://github.com/tvmlabs/tvm-sdk.git', tag = "v2.3.3.an", default-features = false }
tvm_types = { git = 'https://github.com/tvmlabs/tvm-sdk.git', tag = "v2.3.3.an" }
tvm_vm = { git = 'https://github.com/tvmlabs/tvm-sdk.git', tag = "v2.3.3.an", features = ['gosh'] }


database = { path = "database" }
http-server = { path = "http-server" }
message-router = { path = "message-router" }
migration-tool = { path = "migration-tool" }
network = { path = "network" }
node = { path = "node" }
