[package]
name = "network"
edition = "2021"
version = "0.1.0"
rust-version.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
bincode.workspace = true
chitchat.workspace = true
clap.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

quinn = { version = "0.10.2", features = ["rustls"] }
rcgen = "0.11.3"
rustls = { version = "0.21.9", default-features = false, features = ["quic"] }

[dev-dependencies]
rand = "0.8.5"

[features]
# Use automocks in binaries
use_automocks = []
