[package]
name = "http-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
rcgen.workspace = true
salvo.workspace = true
serde_json.workspace = true
tracing.workspace = true
tvm_block.workspace = true
tvm_types.workspace = true
